### PR TITLE
Better Online 1.0.0

### PR DESCRIPTION
**Pull request by reversed-coffee**
Plugin update for Better Online to show online status in more pages.

### CODE REVIEW

**Comment by reversed-coffee** [comment]
Actually, I see a major security flaw with this. Let me fix that real quick.

**Comment by reversed-coffee** [comment]
Added Peanut API to BetterWRD.

**Comment by reversed-coffee** [comment]
There, I took care of it. I usually don't make a mess in the git logs and write sloppy like this 😭

**Comment by davve77** [comment]
sick. i love peanut. excellent work :D

**Comment by davve77** [comment]
also, would you prefer a different image for peanut? i randomly chose one from the results on google but i can change it

**Comment by reversed-coffee** [comment]
> also, would you prefer a different image for peanut? i randomly chose one from the results on google but i can change it

Nah it's fine.

**Pull request merged**
